import "./globals.css";
import { Courgette } from "next/font/google";

const courgette = Courgette({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={courgette.className}>{children}</body>
    </html>
  );
}
